version: '3.9'

services:
  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: new-greenteam
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:prod
